<?Php
$namahari=date("l");
Switch($namahari)
{
Case"Sunday";
Print("Minggu");
print"Waktuuntukistirahat";
Break;
Case"Monday";
Print("Senin<br>");
print"Meetingawalminggujam08.00";
Break;
Case"Tuesday";
Print("Selasa<br>");
print"PembukaanWorkshopDiklat";
Break;
Case"Wednesday";
Print("Rabu<br>");
print("SeminarLaunchigWindowVistadiJHCC");
Break;
Case"Thrusday";
Print("Kamis<br>");
print"PertemuandenganMahasiswa";
Break;
Case"Friday";
Print("Jum’at<br>");
print"Joggingbersama";
Break;
Default:
Print("Sabtu<br>");
print"SurveyhargakeDusit,ManggaDua";
}
?>
</body>
</html>
